#!/usr/bin/env bash
# Stop hook: refuse to call a story finished on assertion alone.
#
# If the story is in GREEN or GATES and the gate suite has not been run since
# the last change to the code the gates judge, block the stop and say so.
# Cheap, and self-clearing: running the gates updates the stamp.
#
# "The code the gates judge" is what gated_stdin in lib.sh keeps: source, test,
# config and the harness's scripts and manifests - never docs, prompts, vendor,
# or anything .gitignore covers. Counting generated output would make the hook
# fire on its own exhaust, which is the same as firing at random; counting a
# command file would charge a gate run for rewording a prompt no gate reads.

set -uo pipefail
HOOK_INPUT="$(cat)"
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh" 2>/dev/null || exit 0

# Never loop on ourselves.
json_is_true stop_hook_active && exit 0

load_state
case "$PHASE" in GREEN|GATES) ;; *) exit 0 ;; esac

reason=""
if [ ! -f "$GATE_STAMP" ]; then
  reason="The gate suite has not been run for story ${STORY_ID}."
else
  # Only the files the gates would have hashed count: a coverage report or a
  # build directory regenerated by an ad-hoc verification run is the gates'
  # own exhaust, not a change to the code they judged. See code_changed_since
  # in lib.sh.
  newer="$(code_changed_since "$GATE_STAMP")"
  [ -n "$newer" ] && reason="Code has changed since the last gate run (e.g. ${newer})."
fi

if [ -z "$reason" ] && grep -q "^RESULT=fail" "$GATE_STAMP" 2>/dev/null; then
  reason="The last gate run for story ${STORY_ID} FAILED."
fi

[ -z "$reason" ] && exit 0

printf '{"decision":"block","reason":"%s"}\n' "$(json_escape "$reason Run the gates before reporting this story complete:

  bash scripts/gates.sh

If a gate fails, fix it or move the story back to RED — do not report GREEN on unverified code. If you are intentionally stopping mid-story, say so explicitly and move the story to a phase that reflects reality.")"
exit 0
